function val(obj, path, def) {
  const parts = path.split('.');
  let cur = obj;
  for (const p of parts) {
    if (cur == null || typeof cur !== 'object') return def;
    cur = cur[p];
  }
  return cur !== undefined && cur !== null ? cur : def;
}

const CodeGenerator = {
  generate(bot, platform) {
    const c = bot.configuration || {};
    return platform === 'mt4' ? this.generateMT4(bot, c) : this.generateMT5(bot, c);
  },

  generateMT4(bot, c) {
    return `//+------------------------------------------------------------------+
//| ${bot.name}.mq4                                                   |
//| Generated by VANTIS AI                                             |
//+------------------------------------------------------------------+

#property strict
#property description "${bot.name} - ${c.strategy} strategy"
#property version   "1.00"

// --- Input Parameters ---
input double RiskPerTrade      = ${val(c, 'moneyManagement.riskPerTrade', 1)};
input double MaxDailyLoss      = ${val(c, 'moneyManagement.maxDailyLoss', 500)};
input double MaxDailyProfit    = ${val(c, 'moneyManagement.maxDailyProfit', 1000)};
input double FixedLotSize      = ${val(c, 'moneyManagement.lotSize', 0.1)};
input int    StopLoss          = ${val(c, 'tradeManagement.stopLoss', 50)};
input int    TakeProfit        = ${val(c, 'tradeManagement.takeProfit', 100)};
input bool   UseTrailing       = ${val(c, 'tradeManagement.trailingStop.enabled', false)};
input int    TrailingPoints    = ${val(c, 'tradeManagement.trailingStop.points', 30)};
input string TradingSymbol     = "${val(c, 'symbol', 'EURUSD')}";
input int    MagicNumber       = 202401;

double g_dailyProfit = 0;
double g_dailyLoss   = 0;

int OnInit() {
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason) {
}

void OnTick() {
   if (!IsNewBar()) return;
   UpdateDailyPL();
   if (g_dailyLoss >= MaxDailyLoss || g_dailyProfit >= MaxDailyProfit) {
      Comment("Daily limit reached");
      return;
   }
${this.mt4StrategyEntry(c)}
}

${this.mt4StrategyFunctions(c)}

bool IsNewBar() {
   static datetime lastBar = 0;
   datetime curBar = iTime(Symbol(), PERIOD_CURRENT, 0);
   if (lastBar != curBar) { lastBar = curBar; return true; }
   return false;
}

void UpdateDailyPL() {
   g_dailyProfit = 0; g_dailyLoss = 0;
   for (int i = 0; i < OrdersTotal(); i++) {
      if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
         if (OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol()) {
            if (OrderProfit() > 0) g_dailyProfit += OrderProfit();
            else g_dailyLoss += MathAbs(OrderProfit());
         }
      }
   }
}

double CalculateLot() {
   double lot = FixedLotSize;
   lot = MathMax(SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX), lot));
   lot = MathRound(lot / SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP)) * SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP);
   return lot;
}
`;
  },

  generateMT5(bot, c) {
    return `//+------------------------------------------------------------------+
//| ${bot.name}.mq5                                                   |
//| Generated by VANTIS AI                                             |
//+------------------------------------------------------------------+

#property description "${bot.name} - ${c.strategy} strategy"
#property version   "1.00"

// --- Input Parameters ---
input double RiskPerTrade      = ${val(c, 'moneyManagement.riskPerTrade', 1)};
input double MaxDailyLoss      = ${val(c, 'moneyManagement.maxDailyLoss', 500)};
input double MaxDailyProfit    = ${val(c, 'moneyManagement.maxDailyProfit', 1000)};
input double FixedLotSize      = ${val(c, 'moneyManagement.lotSize', 0.1)};
input int    StopLoss          = ${val(c, 'tradeManagement.stopLoss', 50)};
input int    TakeProfit        = ${val(c, 'tradeManagement.takeProfit', 100)};
input bool   UseTrailing       = ${val(c, 'tradeManagement.trailingStop.enabled', false)};
input int    TrailingPoints    = ${val(c, 'tradeManagement.trailingStop.points', 30)};
input string TradingSymbol     = "${val(c, 'symbol', 'EURUSD')}";
input ulong  MagicNumber       = 202401;

CTrade   Trade;
CPositionInfo PositionInfo;
CSymbolInfo  SymbolInfo;

double g_dailyProfit = 0;
double g_dailyLoss   = 0;
datetime g_lastBar   = 0;

int OnInit() {
   Trade.SetExpertMagicNumber(MagicNumber);
   Trade.SetDeviationInPoints(10);
   SymbolInfo.Name(Symbol());
   SymbolInfo.Refresh();
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason) {
}

void OnTick() {
   if (!IsNewBar()) return;
   UpdateDailyPL();
   if (g_dailyLoss >= MaxDailyLoss || g_dailyProfit >= MaxDailyProfit) {
      Comment("Daily limit reached");
      return;
   }
${this.mt5StrategyEntry(c)}
}

${this.mt5StrategyFunctions(c)}

bool IsNewBar() {
   datetime curBar = iTime(Symbol(), PERIOD_CURRENT, 0);
   if (g_lastBar != curBar) { g_lastBar = curBar; return true; }
   return false;
}

void UpdateDailyPL() {
   g_dailyProfit = 0; g_dailyLoss = 0;
   for (int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if (PositionSelectByTicket(ticket) && PositionGetInteger(POSITION_MAGIC) == (long)MagicNumber) {
         double profit = PositionGetDouble(POSITION_PROFIT);
         if (profit > 0) g_dailyProfit += profit;
         else g_dailyLoss += MathAbs(profit);
      }
   }
}

double CalculateLot() {
   double lot = FixedLotSize;
   lot = fmax(SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MIN), fmin(SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX), lot));
   lot = MathRound(lot / SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP)) * SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP);
   return lot;
}

bool SendOrder(int type, double lot, double sl, double tp, string comment) {
   double price = (type == ORDER_TYPE_BUY) ? SymbolInfoDouble(Symbol(), SYMBOL_ASK) : SymbolInfoDouble(Symbol(), SYMBOL_BID);
   double slPrice = (type == ORDER_TYPE_BUY) ? price - sl * Point() : price + sl * Point();
   double tpPrice = (type == ORDER_TYPE_BUY) ? price + tp * Point() : price - tp * Point();
   Trade.PositionOpen(Symbol(), type, lot, price, slPrice, tpPrice, comment);
   return Trade.ResultRetcode() == TRADE_RETCODE_DONE;
}
`;
  },

  // ---- MT4 Strategy Code ----
  mt4StrategyEntry(config) {
    switch (config.strategy) {
      case 'grid': return `
   double gridLevels = ${config.grid.gridLevels || 10};
   int count = CountOpen();
   if (count < gridLevels) {
      double lot = CalculateLot();
      OrderSend(Symbol(), OP_BUY, lot, Ask, 10, Ask - StopLoss * Point, Ask + TakeProfit * Point, "Grid Buy", MagicNumber, 0, clrGreen);
      OrderSend(Symbol(), OP_SELL, lot, Bid, 10, Bid + StopLoss * Point, Bid - TakeProfit * Point, "Grid Sell", MagicNumber, 0, clrRed);
   }`;
      case 'martingale': return `
   double lot = CalculateLot();
   if (CountOpen() == 0) {
      OrderSend(Symbol(), OP_BUY, lot, Ask, 10, Ask - StopLoss * Point, Ask + TakeProfit * Point, "Martingale", MagicNumber, 0, clrBlue);
   } else {
      int last = GetLastTicket();
      if (last > 0 && OrderSelect(last, SELECT_BY_TICKET) && OrderProfit() < 0) {
         lot = NormalizeDouble(OrderLots() * ${config.moneyManagement.martingaleMultiplier || 2}, 2);
         lot = MathMin(lot, SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX));
         OrderSend(Symbol(), OP_BUY, lot, Ask, 10, Ask - StopLoss * Point, Ask + TakeProfit * Point, "Martingale", MagicNumber, 0, clrBlue);
      }
   }`;
      case 'hedging': return `
   double lot = CalculateLot();
   int buys = CountType(OP_BUY);
   int sells = CountType(OP_SELL);
   if (buys == 0 && sells == 0) { OrderSend(Symbol(), OP_BUY, lot, Ask, 10, Ask - StopLoss * Point, Ask + TakeProfit * Point, "Hedge Buy", MagicNumber, 0, clrGreen); }
   if (buys > 0 && sells == 0) { OrderSend(Symbol(), OP_SELL, lot, Bid, 10, Bid + StopLoss * Point, Bid - TakeProfit * Point, "Hedge Sell", MagicNumber, 0, clrRed); }
   if (sells > 0 && buys == 0) { OrderSend(Symbol(), OP_BUY, lot, Ask, 10, Ask - StopLoss * Point, Ask + TakeProfit * Point, "Hedge Buy", MagicNumber, 0, clrGreen); }`;
      case 'trend': return `
   if (CountOpen() > 0) return;
   double lot = CalculateLot();
   double maF = iMA(Symbol(), PERIOD_CURRENT, 10, 0, MODE_EMA, PRICE_CLOSE, 1);
   double maS = iMA(Symbol(), PERIOD_CURRENT, 30, 0, MODE_EMA, PRICE_CLOSE, 1);
   double maFp = iMA(Symbol(), PERIOD_CURRENT, 10, 0, MODE_EMA, PRICE_CLOSE, 2);
   double maSp = iMA(Symbol(), PERIOD_CURRENT, 30, 0, MODE_EMA, PRICE_CLOSE, 2);
   if (maFp <= maSp && maF > maS) OrderSend(Symbol(), OP_BUY, lot, Ask, 10, Ask - StopLoss * Point, Ask + TakeProfit * Point, "Trend Buy", MagicNumber, 0, clrGreen);
   if (maFp >= maSp && maF < maS) OrderSend(Symbol(), OP_SELL, lot, Bid, 10, Bid + StopLoss * Point, Bid - TakeProfit * Point, "Trend Sell", MagicNumber, 0, clrRed);`;
      case 'scalping': return `
   if (CountOpen() > 3) return;
   double lot = CalculateLot();
   double rsi = iRSI(Symbol(), PERIOD_M5, 14, PRICE_CLOSE, 0);
   if (rsi < 30) OrderSend(Symbol(), OP_BUY, lot, Ask, 10, Ask - StopLoss * Point, Ask + TakeProfit * Point, "Scalp Buy", MagicNumber, 0, clrGreen);
   if (rsi > 70) OrderSend(Symbol(), OP_SELL, lot, Bid, 10, Bid + StopLoss * Point, Bid - TakeProfit * Point, "Scalp Sell", MagicNumber, 0, clrRed);`;
      default: return `// Strategy: ${config.strategy}`;
    }
  },

  mt4StrategyFunctions(config) {
    let code = `
int CountOpen() {
   int c = 0;
   for (int i = 0; i < OrdersTotal(); i++) {
      if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES) && OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol()) c++;
   }
   return c;
}`;
    if (config.strategy === 'martingale') {
      code += `
int GetLastTicket() {
   int ticket = -1; datetime t = 0;
   for (int i = OrdersTotal() - 1; i >= 0; i--) {
      if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES) && OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol() && OrderOpenTime() > t) {
         t = OrderOpenTime(); ticket = OrderTicket();
      }
   }
   return ticket;
}`;
    }
    if (config.strategy === 'hedging') {
      code += `
int CountType(int type) {
   int c = 0;
   for (int i = 0; i < OrdersTotal(); i++) {
      if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES) && OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol() && OrderType() == type) c++;
   }
   return c;
}`;
    }
    return code;
  },

  // ---- MT5 Strategy Code ----
  mt5StrategyEntry(config) {
    switch (config.strategy) {
      case 'grid': return `
   double gridLevels = ${config.grid.gridLevels || 10};
   int count = CountOpen();
   if (count < gridLevels) {
      double lot = CalculateLot();
      SendOrder(ORDER_TYPE_BUY, lot, StopLoss, TakeProfit, "Grid Buy");
      SendOrder(ORDER_TYPE_SELL, lot, StopLoss, TakeProfit, "Grid Sell");
   }`;
      case 'martingale': return `
   double lot = CalculateLot();
   if (CountOpen() == 0) {
      SendOrder(ORDER_TYPE_BUY, lot, StopLoss, TakeProfit, "Martingale");
   } else {
      ulong last = GetLastTicket();
      if (last > 0) {
         lot = NormalizeDouble(lot * ${config.moneyManagement.martingaleMultiplier || 2}, 2);
         lot = fmin(lot, SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX));
         SendOrder(ORDER_TYPE_BUY, lot, StopLoss, TakeProfit, "Martingale");
      }
   }`;
      case 'hedging': return `
   double lot = CalculateLot();
   int buys = CountType(ORDER_TYPE_BUY);
   int sells = CountType(ORDER_TYPE_SELL);
   if (buys == 0 && sells == 0) { SendOrder(ORDER_TYPE_BUY, lot, StopLoss, TakeProfit, "Hedge Buy"); }
   if (buys > 0 && sells == 0) { SendOrder(ORDER_TYPE_SELL, lot, StopLoss, TakeProfit, "Hedge Sell"); }
   if (sells > 0 && buys == 0) { SendOrder(ORDER_TYPE_BUY, lot, StopLoss, TakeProfit, "Hedge Buy"); }`;
      case 'trend': return `
   if (CountOpen() > 0) return;
   double lot = CalculateLot();
   double maF = iMA(Symbol(), PERIOD_CURRENT, 10, 0, MODE_EMA, PRICE_CLOSE, 1);
   double maS = iMA(Symbol(), PERIOD_CURRENT, 30, 0, MODE_EMA, PRICE_CLOSE, 1);
   double maFp = iMA(Symbol(), PERIOD_CURRENT, 10, 0, MODE_EMA, PRICE_CLOSE, 2);
   double maSp = iMA(Symbol(), PERIOD_CURRENT, 30, 0, MODE_EMA, PRICE_CLOSE, 2);
   if (maFp <= maSp && maF > maS) SendOrder(ORDER_TYPE_BUY, lot, StopLoss, TakeProfit, "Trend Buy");
   if (maFp >= maSp && maF < maS) SendOrder(ORDER_TYPE_SELL, lot, StopLoss, TakeProfit, "Trend Sell");`;
      case 'scalping': return `
   if (CountOpen() > 3) return;
   double lot = CalculateLot();
   double rsi = iRSI(Symbol(), PERIOD_M5, 14, PRICE_CLOSE, 0);
   if (rsi < 30) SendOrder(ORDER_TYPE_BUY, lot, StopLoss, TakeProfit, "Scalp Buy");
   if (rsi > 70) SendOrder(ORDER_TYPE_SELL, lot, StopLoss, TakeProfit, "Scalp Sell");`;
      default: return `// Strategy: ${config.strategy}`;
    }
  },

  mt5StrategyFunctions(config) {
    let code = `
int CountOpen() {
   int c = 0;
   for (int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if (PositionSelectByTicket(ticket) && PositionGetInteger(POSITION_MAGIC) == (long)MagicNumber) c++;
   }
   return c;
}`;
    if (config.strategy === 'martingale') {
      code += `
ulong GetLastTicket() {
   ulong ticket = 0; datetime t = 0;
   for (int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong pt = PositionGetTicket(i);
      if (PositionSelectByTicket(pt) && PositionGetInteger(POSITION_MAGIC) == (long)MagicNumber) {
         datetime ot = (datetime)PositionGetInteger(POSITION_TIME);
         if (ot > t) { t = ot; ticket = pt; }
      }
   }
   return ticket;
}`;
    }
    if (config.strategy === 'hedging') {
      code += `
int CountType(ENUM_POSITION_TYPE type) {
   int c = 0;
   for (int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if (PositionSelectByTicket(ticket) && PositionGetInteger(POSITION_MAGIC) == (long)MagicNumber && (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == type) c++;
   }
   return c;
}`;
    }
    return code;
  }
};

module.exports = CodeGenerator;
